package com.auto.eagenerator.engine

import com.auto.eagenerator.model.*

/**
 * HTML报告生成器 - 回测/优化结果可视化
 */
object HtmlReporter {

    fun generateBacktestReport(report: ReportData): String {
        return """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>${report.strategyName} - 回测报告</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:'Segoe UI',sans-serif;background:#0d1117;color:#c9d1d9;padding:32px}
  h1{color:#58a6ff;margin-bottom:8px}
  h2{color:#f0f6fc;margin:24px 0 12px;border-bottom:1px solid #30363d;padding-bottom:8px}
  .meta{color:#8b949e;margin-bottom:24px}
  .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}
  .card{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:16px}
  .card .label{font-size:12px;color:#8b949e;text-transform:uppercase}
  .card .value{font-size:24px;font-weight:700;margin-top:4px}
  .positive{color:#3fb950}.negative{color:#f85149}.neutral{color:#d2991d}
  table{width:100%;border-collapse:collapse;margin-top:12px}
  th,td{padding:10px 16px;text-align:left;border-bottom:1px solid #30363d}
  th{background:#161b22;color:#8b949e;font-weight:600}
  tr:hover{background:#1c2129}
  .chart{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:16px;margin-top:12px}
</style>
</head>
<body>
<h1>${report.strategyName}</h1>
<div class="meta">${report.symbol} · ${report.timeframe} · ${report.period} · 生成时间: ${report.generatedAt}</div>

<h2>核心指标</h2>
<div class="grid">
  <div class="card"><div class="label">净利润</div><div class="value ${if (report.netProfit >= 0) "positive" else "negative"}">${String.format("%.2f", report.netProfit)}</div></div>
  <div class="card"><div class="label">总交易</div><div class="value neutral">${report.totalTrades}</div></div>
  <div class="card"><div class="label">胜率</div><div class="value ${if (report.winRate >= 50) "positive" else "negative"}">${String.format("%.1f", report.winRate)}%</div></div>
  <div class="card"><div class="label">夏普比率</div><div class="value ${if (report.sharpeRatio >= 1.0) "positive" else "neutral"}">${String.format("%.2f", report.sharpeRatio)}</div></div>
  <div class="card"><div class="label">最大回撤</div><div class="value negative">${String.format("%.2f", report.maxDrawdownPct)}%</div></div>
  <div class="card"><div class="label">盈亏比</div><div class="value ${if (report.profitFactor >= 1.5) "positive" else "neutral"}">${String.format("%.2f", report.profitFactor)}</div></div>
  <div class="card"><div class="label">恢复因子</div><div class="value neutral">${String.format("%.2f", report.recoveryFactor)}</div></div>
  <div class="card"><div class="label">平均交易</div><div class="value ${if (report.avgTrade >= 0) "positive" else "negative"}">${String.format("%.2f", report.avgTrade)}</div></div>
</div>

<h2>交易统计</h2>
<div class="grid">
  <div class="card"><div class="label">多头交易</div><div class="value neutral">${report.longTrades}</div></div>
  <div class="card"><div class="label">空头交易</div><div class="value neutral">${report.shortTrades}</div></div>
  <div class="card"><div class="label">最大连胜</div><div class="value positive">${report.maxConsecutiveWins}</div></div>
  <div class="card"><div class="label">最大连亏</div><div class="value negative">${report.maxConsecutiveLosses}</div></div>
  <div class="card"><div class="label">平均持仓(小时)</div><div class="value neutral">${String.format("%.1f", report.avgHoldHours)}</div></div>
  <div class="card"><div class="label">最大获利</div><div class="value positive">${String.format("%.2f", report.maxProfitTrade)}</div></div>
  <div class="card"><div class="label">最大亏损</div><div class="value negative">${String.format("%.2f", report.maxLossTrade)}</div></div>
  <div class="card"><div class="label">平均获利</div><div class="value positive">${String.format("%.2f", report.avgWin)}</div></div>
</div>

<h2>按周表现</h2>
<table>
<tr><th>星期</th><th>交易数</th><th>净利润</th><th>胜率</th></tr>
${report.weekdayStats.map { "<tr><td>${it.day}</td><td>${it.trades}</td><td class=\"${if (it.profit >= 0) "positive" else "negative"}\">${String.format("%.2f", it.profit)}</td><td>${String.format("%.1f", it.winRate)}%</td></tr>" }.joinToString("\n")}
</table>

${if (report.equityPoints.isNotEmpty()) """
<h2>权益曲线</h2>
<div class="chart">
  <svg width="100%" height="300" viewBox="0 0 800 300">
    <polyline fill="none" stroke="#3fb950" stroke-width="2"
      points="${generateEquitySvgPoints(report.equityPoints, 800, 300)}"/>
  </svg>
</div>
""" else ""}

<p style="margin-top:32px;color:#484f58;font-size:12px">Generated by Marvis EA Generator v6</p>
</body></html>"""
    }

    fun generateOptReport(
        ga: GAResult? = null,
        mc: MCResult? = null,
        wf: WFResult? = null,
        strategyName: String = "Optimization",
    ): String {
        val sections = mutableListOf<String>()

        if (ga != null) {
            sections.add("""
<h2>遗传算法优化</h2>
<div class="grid">
  <div class="card"><div class="label">最优适应度</div><div class="value positive">${String.format("%.4f", ga.bestIndividual.fitness)}</div></div>
  <div class="card"><div class="label">收敛代数</div><div class="value neutral">${ga.convergenceGen}</div></div>
  <div class="card"><div class="label">最优参数</div><div class="value" style="font-size:14px">${ga.bestIndividual.genes.joinToString(", ") { String.format("%.2f", it) }}</div></div>
</div>""")
        }

        if (mc != null) {
            sections.add("""
<h2>蒙特卡洛分析</h2>
<div class="grid">
  <div class="card"><div class="label">原始夏普</div><div class="value positive">${String.format("%.2f", mc.originalSharpe)}</div></div>
  <div class="card"><div class="label">模拟均值夏普</div><div class="value neutral">${String.format("%.2f", mc.meanSharpe)}</div></div>
  <div class="card"><div class="label">夏普标准差</div><div class="value neutral">${String.format("%.2f", mc.stdSharpe)}</div></div>
  <div class="card"><div class="label">稳健性评分</div><div class="value ${if (mc.robustnessScore >= 0.8) "positive" else if (mc.robustnessScore >= 0.5) "neutral" else "negative"}">${String.format("%.2f", mc.robustnessScore)}</div></div>
  <div class="card"><div class="label">95%置信区间</div><div class="value neutral" style="font-size:14px">[${String.format("%.2f", mc.confidenceInterval.first)}, ${String.format("%.2f", mc.confidenceInterval.second)}]</div></div>
</div>""")
        }

        if (wf != null) {
            sections.add("""
<h2>前进式优化</h2>
<div class="grid">
  <div class="card"><div class="label">样本内平均夏普</div><div class="value positive">${String.format("%.2f", wf.avgInSharpe)}</div></div>
  <div class="card"><div class="label">样本外平均夏普</div><div class="value ${if (wf.avgOutSharpe >= wf.avgInSharpe * 0.7) "positive" else "negative"}">${String.format("%.2f", wf.avgOutSharpe)}</div></div>
  <div class="card"><div class="label">参数稳定性</div><div class="value ${if (wf.stability >= 0.7) "positive" else "neutral"}">${String.format("%.2f", wf.stability)}</div></div>
  <div class="card"><div class="label">样本外稳健性</div><div class="value ${if (wf.robustness >= 0.7) "positive" else "neutral"}">${String.format("%.2f", wf.robustness)}</div></div>
</div>
<h2>各窗口详情</h2>
<table><tr><th>窗口</th><th>样本内(K线)</th><th>样本外(K线)</th><th>IS夏普</th><th>OOS夏普</th></tr>
${wf.windows.map { "<tr><td>${it.index}</td><td>${it.inStart}-${it.inEnd}</td><td>${it.outStart}-${it.outEnd}</td><td>${String.format("%.2f", it.inSampleSharpe)}</td><td class=\"${if (it.outSampleSharpe >= it.inSampleSharpe * 0.6) "positive" else "negative"}\">${String.format("%.2f", it.outSampleSharpe)}</td></tr>" }.joinToString("\n")}
</table>""")
        }

        return """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>$strategyName - 优化报告</title>
<style>*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',sans-serif;background:#0d1117;color:#c9d1d9;padding:32px}
h1{color:#58a6ff;margin-bottom:24px}
h2{color:#f0f6fc;margin:24px 0 12px;border-bottom:1px solid #30363d;padding-bottom:8px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px}
.card{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:16px}
.card .label{font-size:12px;color:#8b949e;text-transform:uppercase}
.card .value{font-size:22px;font-weight:700;margin-top:4px}
.positive{color:#3fb950}.negative{color:#f85149}.neutral{color:#d2991d}
table{width:100%;border-collapse:collapse;margin-top:12px}
th,td{padding:10px 16px;text-align:left;border-bottom:1px solid #30363d}
th{background:#161b22;color:#8b949e;font-weight:600}
tr:hover{background:#1c2129}
p.footer{margin-top:32px;color:#484f58;font-size:12px}
</style></head><body>
<h1>$strategyName</h1>
${sections.joinToString("\n")}
<p class="footer">Generated by Marvis EA Generator v6</p>
</body></html>"""
    }

    private fun generateEquitySvgPoints(points: List<Double>, width: Int, height: Int): String {
        if (points.size < 2) return ""
        val min = points.min()
        val max = points.max()
        val range = (max - min).coerceAtLeast(1.0)
        return points.mapIndexed { i, v ->
            val x = (i.toDouble() / (points.size - 1)) * width
            val y = height - ((v - min) / range) * (height - 20) - 10
            "${x.toInt()},${y.toInt()}"
        }.joinToString(" ")
    }

    data class WeekdayStat(val day: String, val trades: Int, val profit: Double, val winRate: Double)

    data class ReportData(
        val strategyName: String = "Strategy",
        val symbol: String = "EURUSD",
        val timeframe: String = "H1",
        val period: String = "",
        val generatedAt: String = "",
        val netProfit: Double = 0.0,
        val totalTrades: Int = 0,
        val winRate: Double = 0.0,
        val sharpeRatio: Double = 0.0,
        val maxDrawdownPct: Double = 0.0,
        val profitFactor: Double = 0.0,
        val recoveryFactor: Double = 0.0,
        val avgTrade: Double = 0.0,
        val longTrades: Int = 0,
        val shortTrades: Int = 0,
        val maxConsecutiveWins: Int = 0,
        val maxConsecutiveLosses: Int = 0,
        val avgHoldHours: Double = 0.0,
        val maxProfitTrade: Double = 0.0,
        val maxLossTrade: Double = 0.0,
        val avgWin: Double = 0.0,
        val weekdayStats: List<WeekdayStat> = emptyList(),
        val equityPoints: List<Double> = emptyList(),
    )
}
